### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by BytewaveMLP** [LordNature/Atlas#1]
The repo only has a LICENSE and README file and it's been a day omg pls fix there are pressing issues with this software is the author dead???!/1/1?!/?!/!/!?!?1/!?1/?!/!/!?!/!!

**Comment by LordNature** [comment]
@BytewaveMLP Sorry, past two days I've been ill. I'll release a patch right away!

**Comment by LordNature** [comment]
@BytewaveMLP Fixed!
