### ISSUE TITLE
Move to discord.py

### ISSUE THREAD

**Issue by BytewaveMLP** [LordNature/Atlas#2]
Everyone knows python is a better language lol

you should use python

did I mention python?

pyyyyythhhoooooonnnnnnnn~

**Comment by antigravities** [comment]
No Python good language but JavaScript best language 👎

**Comment by BytewaveMLP** [comment]
@antigravities ![](https://i.imgflip.com/1dxet4.jpg)

**Comment by antigravities** [comment]
Python is a bad hombre. Gotta send him back to the border and Make JavaScript Great Again

**Comment by BytewaveMLP** [comment]
![](https://dab1nmslvvntp.cloudfront.net/wp-content/uploads/2015/06/1435405133B83LZQLIYAAHVzJ.png "You've got a long way to go")

**Comment by BytewaveMLP** [comment]
(yes, i know we've been over that before)

**Comment by antigravities** [comment]
That lack of a closing parenthesis is really bothering me
edit: there you go, pally

**Comment by BytewaveMLP** [comment]
Fixed, shipping for `comment` 1.2.1

**Comment by BytewaveMLP** [comment]
How about we settle on C#?

**Comment by LordNature** [comment]
@BytewaveMLP Eww C#? That's bracket hell.

**Comment by LordNature** [comment]
Sticking with Discord.js.

**Comment by antigravities** [comment]
Good choice. ;)

**Comment by LordNature** [comment]
@antigravities Thanks ;)
@BytewaveMLP Javascript is a picky language, but it means well.

**Comment by BytewaveMLP** [comment]
@LordNature Python **isn't** a quirky language and means well. :3

**Comment by antigravities** [comment]
Byte can we stop fighting about this and admit that JavaScript won

**Comment by BytewaveMLP** [comment]
@antigravities Never!
